# Generated by Django 4.2.2 on 2023-06-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'verbose_name': 'Categoría de productos', 'verbose_name_plural': 'Categorías de productos'},
        ),
    ]
