# Generated by Django 4.2.2 on 2023-06-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_de_medida',
        ),
    ]
