# Generated by Django 4.2.2 on 2023-06-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_rename_cantidad_producto_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='modelo',
        ),
    ]
