# Generated by Django 4.2.2 on 2023-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_rename_nombre_producto_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
