# Generated by Django 4.2.2 on 2023-06-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_ofertas_imagen_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
