# Generated by Django 4.2.2 on 2023-06-15 00:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_de_publicacion_oferta', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de publicación de la oferta')),
                ('imagen_oferta', models.ImageField(blank=True, null=True, upload_to='celulares')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Producto')),
            ],
        ),
        migrations.AlterField(
            model_name='productocategoria',
            name='descripcion_producto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='descripción'),
        ),
        migrations.DeleteModel(
            name='Ofertas',
        ),
    ]
