# Generated by Django 4.2.2 on 2023-06-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_oferta_alter_productocategoria_descripcion_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nuevo precio con descuento'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='imagen_oferta',
            field=models.ImageField(blank=True, null=True, upload_to='ofertas'),
        ),
    ]
